#!/bin/bash

########################################################################
#                             T R O K A M
#                  Free and Open Source Search Engine
# 
#  Service        http://trokam.com
#  Development    http://dev.trokam.com
#  Repository     https://github.com/trokam
# 
#  Copyright (C) 2015, Nicolas Slusarenko
#                      nicolas.slusarenko@trokam.com
# 
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  any later version.
# 
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
########################################################################

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Create directory
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

mkdir -p $HOME/log/

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# The loop
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

while [ 1 ]
do
    LOG_FILE=$HOME'/log/cruncher_'$(date +%Y_%m_%d_%H%M%S)'.log'
    cruncher --log-level=TRACE --page-limit=1000 > $LOG_FILE
done
